# Generated by Django 5.1.1 on 2024-09-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='archivo_plano',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='nombre_plano',
        ),
        migrations.AddField(
            model_name='plano',
            name='imagen',
            field=models.ImageField(default='', upload_to='planos/'),
            preserve_default=False,
        ),
    ]
