# Generated by Django 5.1.1 on 2025-06-21 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='id_plano',
        ),
    ]
