# Generated by Django 5.1.1 on 2024-11-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='forma',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
