# Generated by Django 5.1.1 on 2024-10-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0002_remove_plano_archivo_plano_remove_plano_nombre_plano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('agente', 'Agente Inmobiliario'), ('usuario', 'Usuario')], default='usuario', max_length=10),
        ),
    ]
