# Generated by Django 5.1.1 on 2025-06-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0003_alter_plano_fecha_subida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logactividad',
            name='tipo_accion',
            field=models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('registro', 'Registro'), ('subir', 'Subir Archivo'), ('venta', 'Venta'), ('consultar', 'Consultar'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
