# Generated by Django 5.1.1 on 2024-10-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='nombre_plano',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
