# Generated by Django 5.1.1 on 2024-10-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0004_plano_nombre_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
